using System;
using DBManager.DBManually;
using DBManager.DBManually.DataAnnotation;

namespace DBManager
{
    public class autosgrsm_som : DBManuallyManager
    {
        //FLOWID;TECNOLOGIA;OPERACION_COMERCIAL;"ESTADO DE LA ORDEN";APPOINTMENT_ID;FLOWNO;ORDERCREATETIME;WORKCREATETIME;DATE_ERROR;FLOWTYPE;FLOWTYPEID;PROCESSINSTNAME;ACTIVITYDEFID;ACTIVITYINSTNAME;CRMNO;CUSTOMNAME;PRODUCT;OPERATION;ACCESSACCOUNT;INSTALL_ADDRESS;"CODIGO LOCALIDAD";ERROR_CODE;ERROR_DESC
    }
}
